name: ZeltCmds
main: de.zeltclan.tare.zeltcmds.ZeltCmds
version: 1.5.1
description: Just have the commands you really need
author: Tare
commands:
   zeltcmds:
      description: Manage your commands
      usage: Use /zeltcmds for help
      permission: zeltcmds.manage
      permission-message: You don't have the permission for this command
permissions:
   zeltcmds.manage:
      description: Allows to manage commands
      default: op